version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=stockspree
      - MARIADB_USER=stockspree
      - MARIADB_PASSWORD=stockspree
      - MARIADB_ROOT_PASSWORD=stockspree
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=stockspree
      - PMA_PASSWORD=stockspree
    ports:
      - "8081:80"
    depends_on:
      - mariadb
  stockspree-app:
    image: stockspree-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9010:9010"
    volumes:
      - .:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/stockspree
      - SPRING_DATASOURCE_USERNAME=stockspree
      - SPRING_DATASOURCE_PASSWORD=stockspree
    depends_on:
      - mariadb

volumes:
  mariadb_data: 