# FROM eclipse-temurin:21-jdk
# WORKDIR /app
# COPY . .
# EXPOSE 9010
# CMD ["./mvnw", "spring-boot:run"] 

FROM openjdk:21-jdk-slim AS build

WORKDIR /app


RUN apt-get update && apt-get install -y maven
ENTRYPOINT ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=prod"]
